export const pseudocode = {
  bubble: [
    'for i = 0 to n-1',
    '  for j = 0 to n-1-i',
    '    if arr[j] > arr[j+1]',
    '      swap(arr[j], arr[j+1])',
    '    end if',
    '  end for',
    'end for',
    'return sorted array',
  ],
  merge: [
    'mergeSort(arr, l, r):',
    '  if l >= r: return',
    '  m = (l + r) / 2',
    '  mergeSort(arr, l, m)',
    '  mergeSort(arr, m+1, r)',
    '  merge(arr, l, m, r)',
    '    compare left[i] vs right[j]',
    '    place smaller element',
    '  return merged array',
  ],
  quick: [
    'quickSort(arr, low, high):',
    '  if low < high:',
    '    pivot = arr[high]',
    '    i = low - 1',
    '    for j = low to high-1',
    '      if arr[j] <= pivot: swap(i++, j)',
    '    swap(i+1, high)  // place pivot',
    '    quickSort(arr, low, pi-1)',
    '    quickSort(arr, pi+1, high)',
  ],
  heap: [
    'heapSort(arr):',
    '  buildMaxHeap(arr)',
    '    heapify(arr, n, i)',
    '      find largest among i, 2i+1, 2i+2',
    '    swap if needed, recurse',
    'for i = n-1 to 1:',
    '  swap(arr[0], arr[i])',
    '  heapify(arr, i, 0)',
    'return sorted array',
  ],
  linear: [
    'linearSearch(arr, target):',
    '  for i = 0 to n-1',
    '    if arr[i] == target: return i',
    '  end for',
    '  return -1',
  ],
  binary: [
    'binarySearch(arr, target):',
    '  low = 0, high = n-1',
    '  while low <= high:',
    '    mid = (low + high) / 2',
    '    if arr[mid] == target: return mid',
    '    else if arr[mid] < target: low = mid+1',
    '    else: high = mid-1',
    '  return -1',
  ],
  bfs: [
    'BFS(graph, source):',
    '  queue = [source], visited = {source}',
    '  while queue not empty:',
    '    node = queue.dequeue()',
    '    for each neighbor of node:',
    '      if not visited: enqueue, mark visited',
  ],
  dfs: [
    'DFS(graph, source):',
    '  stack = [source]',
    '  while stack not empty:',
    '    node = stack.pop()',
    '    if not visited: mark, push neighbors',
  ],
  dijkstra: [
    'Dijkstra(graph, source):',
    '  dist[source] = 0, all others = ∞',
    '  priority queue with all nodes',
    '  while pq not empty:',
    '    u = node with min dist',
    '    for each neighbor v of u:',
    '      if dist[u] + w(u,v) < dist[v]:',
    '        dist[v] = dist[u] + w(u,v)',
  ],
  astar: [
    'A*(graph, source, target):',
    '  open = {source}, g[source] = 0',
    '  f[n] = g[n] + h(n)',
    '  while open not empty:',
    '    current = node with min f',
    '    if current == target: return path',
    '    for each neighbor:',
    '      update g, f if better path found',
  ],
  'bst-insert': [
    'BST Insert(val):',
    '  if tree empty: create root',
    '  if val < current: go left',
    '  if val > current: go right',
    '  insert at null position',
  ],
  'bst-delete': [
    'BST Delete(val):',
    '  find node with val',
    '  if leaf: remove directly',
    '  if one child: replace with child',
    '  if two children:',
    '    find inorder successor',
    '    replace val, delete successor',
  ],
  'bst-inorder': [
    'Inorder(node):',
    '  Inorder(node.left)',
    '  visit(node)',
    '  Inorder(node.right)',
  ],
  'bst-preorder': [
    'Preorder(node):',
    '  visit(node)',
    '  Preorder(node.left)',
    '  Preorder(node.right)',
  ],
  'bst-postorder': [
    'Postorder(node):',
    '  Postorder(node.left)',
    '  Postorder(node.right)',
    '  visit(node)',
  ],
}
